// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5U4ByvNMrih6NLWivHbqIdUADFOKKmKQ',
    appId: '1:556238091932:web:2c9150a74866eb73eb5f59',
    messagingSenderId: '556238091932',
    projectId: 'shoppy-7d5ea',
    authDomain: 'shoppy-7d5ea.firebaseapp.com',
    storageBucket: 'shoppy-7d5ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4iy82OzADAG_gsM5Md6GlouIPTTLK7k',
    appId: '1:556238091932:android:c99ca4c9c602b2dfeb5f59',
    messagingSenderId: '556238091932',
    projectId: 'shoppy-7d5ea',
    storageBucket: 'shoppy-7d5ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkeSuiiVxh_bN10KQ2NU4kZrrdzb-saPo',
    appId: '1:556238091932:ios:64ec0d6bb2279a61eb5f59',
    messagingSenderId: '556238091932',
    projectId: 'shoppy-7d5ea',
    storageBucket: 'shoppy-7d5ea.appspot.com',
    iosBundleId: 'com.example.shoppy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkeSuiiVxh_bN10KQ2NU4kZrrdzb-saPo',
    appId: '1:556238091932:ios:64ec0d6bb2279a61eb5f59',
    messagingSenderId: '556238091932',
    projectId: 'shoppy-7d5ea',
    storageBucket: 'shoppy-7d5ea.appspot.com',
    iosBundleId: 'com.example.shoppy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5U4ByvNMrih6NLWivHbqIdUADFOKKmKQ',
    appId: '1:556238091932:web:f56587aaf11bbe1aeb5f59',
    messagingSenderId: '556238091932',
    projectId: 'shoppy-7d5ea',
    authDomain: 'shoppy-7d5ea.firebaseapp.com',
    storageBucket: 'shoppy-7d5ea.appspot.com',
  );

}